Traceback (most recent call last):
  File "c:\users\andrea\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\andrea\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\andrea\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\andrea\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\andrea\anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\users\andrea\anaconda3\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\andrea\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\andrea\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#lib
import xarray as xr 
from lib.plots_dwts import colorp,  custom_colorp,Plot_DWTs_Mean_Anom, Plot_DWTs_totalmean,\
Plot_Probs_WT_WT, Plot_Probs_WT_WT_anomaly, Plot_Probs_WT_WT_WT, Plot_DWTs_Probs, \
Report_Sim_oneyear, Report_Sim, Plot_DWTs_counts, Chrono_dwts_tcs, Chrono_probs_tcs, Plot_dwts_colormap

from lib.predictor_definition_building import SP_genesis_cat,storms_sp

import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-75e1722da373>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m#lib[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;32mimport[0m [0mxarray[0m [1;32mas[0m [0mxr[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 3[1;33m [1;32mfrom[0m [0mlib[0m[1;33m.[0m[0mplots_dwts[0m [1;32mimport[0m [0mcolorp[0m[1;33m,[0m  [0mcustom_colorp[0m[1;33m,[0m[0mPlot_DWTs_Mean_Anom[0m[1;33m,[0m [0mPlot_DWTs_totalmean[0m[1;33m,[0m[0;31m\[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [0mPlot_Probs_WT_WT[0m[1;33m,[0m [0mPlot_Probs_WT_WT_anomaly[0m[1;33m,[0m [0mPlot_Probs_WT_WT_WT[0m[1;33m,[0m [0mPlot_DWTs_Probs[0m[1;33m,[0m[0;31m [0m[0;31m\[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mReport_Sim_oneyear[0m[1;33m,[0m [0mReport_Sim[0m[1;33m,[0m [0mPlot_DWTs_counts[0m[1;33m,[0m [0mChrono_dwts_tcs[0m[1;33m,[0m [0mChrono_probs_tcs[0m[1;33m,[0m [0mPlot_dwts_colormap[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'lib.plots_dwts'
ModuleNotFoundError: No module named 'lib.plots_dwts'

